### ISSUE TITLE
how to copy on something else other than click

### ISSUE THREAD

**Issue by ctf0** [Inndy/vue-clipboard2#10]
atm the lib support only copying on click event, but what if we want to change that to something like `click.ctrl` or any other event ?

in the original clipboard.js u can use `data-clipboard-text` and use any event to call
`new Clipboard(.itemClass)`

**Comment by Inndy** [comment]
Do you have any idea? I think we can add a global method like `this.$copyText(text)`

**Comment by ctf0** [comment]
that would surely work & maybe have a second option like add the event as a second prop to the attribute it self `v-clipboard:copy="message, 'click.ctrl'"`

**Comment by Inndy** [comment]
that will be a little challenging since I have to bind DOM events by my self. I will add `$copyText` method these days

**Comment by ctf0** [comment]
okay np, any time frame when will it be available ?

**Comment by Inndy** [comment]
`$copyText` is available in v0.0.7, check README before use it!

**Comment by ctf0** [comment]
working perfectly except for one part, in the old i could refocus the input again with `e.trigger.focus()` but using with the new option

```js
this.$copyText(this.getKey(key)).then((e) => {
    e.trigger.focus()
})
```

doesnt work.

if u have a tip on how to get it work i would deeply appreciate it, otherwise we can close this ticket.

**Comment by ctf0** [comment]
as `this.$copyText(text)` will be used inside an event function anyway, we can pass the original event as second param and the lib will then use it to populate the correct trigger.

**Comment by ctf0** [comment]
using the code inside nexttick gives error
```js
copyLink(path) {
    this.$nextTick(() => {
        console.log(path)
        this.$copyText(path)
    })
}
```
```bash
Uncaught (in promise) {action: "copy", text: "abc", trigger: button, clearSelection: ƒ}
```

**Comment by Inndy** [comment]
Clipboard.js doesn't expose their internal API (i.e. `ClipboardAction` class) but just `Clipbaord` class. It will be hard to deal with if I want to use Clipboard.js without modifying anything.

Maybe use `Vue.nexttick` can solve your refocus problem?

**Comment by ctf0** [comment]
np, i got it fixed with `$event.target.focus()`. thanx again for ur work :+1:
