### ISSUE TITLE
Vue version in package.json is too generic

### ISSUE THREAD

**Issue by robyedlin** [Inndy/vue-clipboard2#12]
Using `"vue": "2"` is causing versioning issues with frameworks like Nuxt.

Related: https://github.com/nuxt/nuxt.js/issues/2079

**Comment by Inndy** [comment]
Due to Vue API is stable under same major release, I think it should not be a problem and it just work fine with all Vue 2.x releases. If you have a problem with this, you can add Vue dependency with specific version into your own project.
