### ISSUE TITLE
I use requirejs introduced but the error

### ISSUE THREAD

**Issue by linguangyu** [Inndy/vue-clipboard2#14]
![image](https://user-images.githubusercontent.com/24983193/33926627-de326524-e019-11e7-91e7-ff96ed668044.png)

![image](https://user-images.githubusercontent.com/24983193/33926649-ed160c30-e019-11e7-9de1-809d1b261af3.png)

![image](https://user-images.githubusercontent.com/24983193/33926679-0b45918a-e01a-11e7-8f5a-a2d94681b043.png)

**Comment by Inndy** [comment]
See [browserify-me.js](https://github.com/Inndy/vue-clipboard2/blob/v0.0.8/browserify-me.js), load VueClipboard and `Vue.use(VueClipboard)` by yourself instead of loading browseriy-ed version.

**Comment by Inndy** [comment]
@linguangyu problem solved yet?

**Comment by Inndy** [comment]
Consider problem solved. If still need help, you can re-open this issue.
