### ISSUE TITLE
Uncaught (in promise) when using chrome device toolbar

### ISSUE THREAD

**Issue by ctf0** [Inndy/vue-clipboard2#15]
am using `this.$copyText(path)` to copy a link to clipboard.

on normal usage "desktop" no errors, but when switching to the devices toolbar the error shows up on each click.

**Comment by Inndy** [comment]
Can you provide more details to reproduce this problem?

**Comment by ctf0** [comment]
- `<div @click="this.$copyText('abc')">click me</div>`
- open chrome dev and click on `toggle device toolbar` at the top left
- click the div and watch the console.
