### ISSUE TITLE
Copy HTML Text vs Plain Text

### ISSUE THREAD

**Issue by formatically** [Inndy/vue-clipboard2#17]
Is there any way to copy text as text/html instead of the default text/plain?

When I copy text like "This is a <i>test</i>", the italic tags are copied too instead of them being styled. 

It appears that clipboard.js is able to do this.  Is this also possible with vue-clipboard?

Thanks!

**Comment by Inndy** [comment]
Get html DOM ref and read `innerHTML`, then copy your html code by `Vue.$copyText`

Ref: https://stackoverflow.com/questions/43537121/how-to-get-html-content-of-component-in-vue-js/43537989
