### ISSUE TITLE
How can I use this.$copyText in async method?

### ISSUE THREAD

**Issue by springxiege** [Inndy/vue-clipboard2#20]
I can't use this plugin in my app. Do you have any good ideas? otherwise, I have use it like this: 
``` js
// app.ts
import VueClipboard from 'vue-clipboard2';
Vue.use(VueClipboard);

// component.vue
<template>
<button @click="doCopy">Copy</button>
</template>
export default Vue.extend({
 name: '',
 data: {},
 methods: {
  async doCopy(){
    this.$copyText('copy content').then(function(e){console.log(e)})
  }
 }
})

```
Do you have any ideas for making it work in async function?

**Comment by springxiege** [comment]
I have done like this, but trigger the  error event. copy failed

**Comment by Inndy** [comment]
You can not use `$copyText` in async method, please read README and https://github.com/zenorocha/clipboard.js/wiki/Known-Limitations
