### ISSUE TITLE
Could I copay all content of `div tag`?

### ISSUE THREAD

**Issue by thearabbit** [Inndy/vue-clipboard2#25]
I would like to copay all content of `div tag` like this
```
<div id="copyHear">
   <h1>Hello</h1>
   <table>.......
   .........
</div>
```

**Comment by Inndy** [comment]
What do you mean? Copy `innerHTML` of `#copyHear`?

```javascript
new Vue({
  ...somecode,
  methods: {
    onClick () {
      this.$copyText(document.querySelector('#copyHear').innerHTML) // or outerHTML?
    }
  }
})
```

**Comment by thearabbit** [comment]
Yes, would copy of `#copyHear`.
I will try soon 👍

**Comment by Inndy** [comment]
If you need text content instead, use `textContent` attribute.

**Comment by Inndy** [comment]
@thearabbit If you solved your problem, please close the issue. Or I will close it later.

**Comment by thearabbit** [comment]
Sorry, have a bit busy.
Please wait

**Comment by thearabbit** [comment]
It work fine.
but could I use `ref` instead of `document.querySelector('#copyHear').innerHTML`?
```
<div ref="copyHear">
   <h1>Hello</h1>
   <table>.......
   .........
</div>
-----
methods: {
    onClick () {
      this.$copyText(this.$refs........)
    }
  }
```
Please advise

**Comment by thearabbit** [comment]
Very thanks, 😄
