### ISSUE TITLE
Uncaught ReferenceError: VueClipboard 

### ISSUE THREAD

**Issue by tupphelper** [Inndy/vue-clipboard2#34]
Hello, this my code attempting to set up use of Vue clipboard, note this is cdn because its a completely standalone page with no back end what so ever. I know nothing about webpack or any of the other massively complex packages i've seen that actually support these "20 lines or less" examples. 

````html
  <script type="text/javascript" src="https://unpkg.com/vue"></script>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/vue-clipboards@1.2.4/dist/vue-clipboards.min.js">
  </script>
<script>

 Vue.use(VueClipboard)
````
When I load the page i get this in the console
````
 Uncaught ReferenceError: VueClipboard is not defined
    at html:80
``````
How do I actually reference the code you have packaged here? Why does Vue work just fine from a cdn but I cannot reference anything in the second one?

**Comment by Inndy** [comment]
You used wrong package `vue-clipboards` which is not `vue-clipboard2`

**Comment by tupphelper** [comment]
Ok that did in fact resolve the VueClipboard reference error. Its digging into code from the CDN. Do you know where I can resolve an issue with vue-clipboard.js using the "require" function? Or am I just wasting my time trying to get this to work in a stand alone environment? I believe that technically vue-clipboard isn't you so I don't want to ask you to fix it but "require" is node.js according to my google search.

**Comment by Inndy** [comment]
Here is a example using standalone js file: http://jsbin.com/behecujoze/edit?html,output

**Comment by tupphelper** [comment]
Yay it works! Thanks!
