### ISSUE TITLE
If it existed after ajax an error will occur ！

### ISSUE THREAD

**Issue by BengBu-YueZhang** [Inndy/vue-clipboard2#35]
``
// success
this.url = 'http://test.czbapp.com/paymentonline'
this.$copyText(this.url).then(function (e) {
   console.log('成功')
 }, function (e) {
    console.log('失败')
 })
await Contract.order.copyH5PayLink(id)
``

``
// error
await Contract.order.copyH5PayLink(id)
this.url = 'http://test.czbapp.com/paymentonline'
this.$copyText(this.url).then(function (e) {
   console.log('成功')
 }, function (e) {
    console.log('失败')
 })
``

**Comment by Inndy** [comment]
`$copyText` method will not work in async method (i.e. AJAX callback)

Ref: zenorocha/clipboard.js#218, https://github.com/zenorocha/clipboard.js/wiki/Known-Limitations
