### ISSUE TITLE
autoSetContainer opion impossible to set to true

### ISSUE THREAD

**Issue by LeKristapino** [Inndy/vue-clipboard2#36]
It seems that documentation is incorrect about being able to set `VueClipboard.config.autoSetContainer` because in the code it is set through  an independent variable and when setting `container` option this variable is checked instead of `VueClipboard.config.autoSetContainer`

```
var VueClipboardConfig = {
  autoSetContainer: false
};
```

Also `VueClipboard.config` evaluates to `udnefined`

**Comment by Inndy** [comment]
Fixed in 6b61a30db93220cc5eb3593cdf243551d45145ce, upgrade to v0.2.1 should fix this.
