### ISSUE TITLE
how to preserve text format

### ISSUE THREAD

**Issue by ctf0** [Inndy/vue-clipboard2#39]
for example if i copied a text with a char like `=>` the copied text will become `=&gt;`, so is there a way to add an option to disable that ?

**Comment by ctf0** [comment]
try something like 
```js
let txt = 'abc => test '

// now try to copy it 
this.$copyText(txt)
```

paste the data and check the output.

**Comment by ctf0** [comment]
@Inndy any update ?

**Comment by Inndy** [comment]
I'm busy these days, it would take some efforts to fix this due to it must add a new DOM to current document body. It may cause some problem (like triggering unwanted event callback or something else). I will try to fix `$copyText` later.

**Comment by Inndy** [comment]
https://codepen.io/anon/pen/wEEBor
https://codesandbox.io/s/64xo8n4163

Can't reproduce with latest `vue-clipbaord2@0.2.1`

**Comment by ctf0** [comment]
all good, does it require any extra configs ?

**Comment by Inndy** [comment]
As you can see, [latest release](https://github.com/Inndy/vue-clipboard2/releases/tag/v0.2.1) was made at Jul, and I did not change any code. Just use it as the same.

BTW, I had added eslint to this project, so perhaps we can have less silly bug like #36.

**Comment by ctf0** [comment]
oh am sorry, totally forgot its the already released version,

am using with `this.$copyText()` maybe the usage is different than the normal ?

**Comment by Inndy** [comment]
I think you should check your code if Laravel already did the HTML entity encode.

**Comment by ctf0** [comment]
actually laravel has nothing to do with it, i simply use `this.$copyText(item.innerHTML)`

**Comment by Inndy** [comment]
Use `item.textContent` instead, or you will get HTML entity encoded string.

**Comment by ctf0** [comment]
awesome, many many thanx for the quick help 🏆
