### ISSUE TITLE
[Vue warn]: Failed to resolve directive: clipboard

### ISSUE THREAD

**Issue by abooayoob** [Inndy/vue-clipboard2#4]
[Vue warn]: Failed to resolve directive: clipboard

I am getting this issue sometimes, but mostly not. And it causes the copying functionality to not work. It is really hard to debug, because it happens very rarely.

I do not know if this is an issue with vue-clipboard2 itself or if it is a vue thing, but I have no clue because I am pretty new to vue in general. Can I listen to this warning in javascript?

**Comment by Inndy** [comment]
How do you use vue-clipboard2? With webpack or just load script from pre-compiled version?

**Comment by abooayoob** [comment]
I am using it like this:

```
npm install --save vue-clipboard2
```

and then:
```
import Vue from 'vue';
import VueClipboard from 'vue-clipboard2';

Vue.use(VueClipboard);
```

But I am not using webpack. Don´t see how that has any impact? It works 95% of the time, but sometimes it doesn´t.

**Comment by Inndy** [comment]
Weird. I use `vue-cli` to create my projects with webpack as building system, and everything just works. What bundler did you use?

**Comment by Inndy** [comment]
@abooayoob How's going with this issue? Did you solve the problem?

**Comment by adwerrd** [comment]
@abooayoob try `npm install clipboard`

**Comment by Inndy** [comment]
Thanks @adwerrd.

I found that I forgot to add `clipboard` as dependency in first release. @abooayoob you can fix this issue by upgrade `vue-clipboard2` and run `npm install` again.

**Comment by mtilokani** [comment]
Hi, I am still this following issue:

[Vue warn]: Failed to resolve directive: clipboard 
(found in <Anonymous> - use the "name" option for better debugging messages.)

I had latest version that is 0.0.6

Please help..

**Comment by alon-kedar** [comment]
I just started using vue two days ago and i had the same issue
the problem was that I declared the VueClipboard global variable on src/main.js
i moved it to the file of the main app component  and then it worked well

**Comment by bhattShankee** [comment]
I ve problem like this .please help me how to solve it.
Vue warn]: Failed to resolve directive: link

**Comment by Inndy** [comment]
@bhattShankee

We don't have any directive named `link`, this is not a part of `vue-clipboard2`.
You may find something like `v-link=` in your source code, try to remove it.

**Comment by Inndy** [comment]
@mtilokani 
How did you include `vue-clipboard2` in your project?
Can you open a new issue (or send me an email) and show me the code?

**Comment by god-lin** [comment]
@alon-kedar  the way you do is well work. 三克油

**Comment by sweetme** [comment]
I ve problem like this .please help me how to solve it.
[Vue warn]: Failed to resolve directive: clipboard
`
import VueClipboard from 'vue-clipboard2'
Vue.use(VueLazyLoad,VueClipboard);
`
