### ISSUE TITLE
Uncaught (in promise) Error: [vue-clipboards] Invalid value. Please use a valid value.

### ISSUE THREAD

**Issue by YiniXu9506** [Inndy/vue-clipboard2#42]
Since I use v-if in my DOM, vue clipboards will throw an error like this when the copy-text-data haven't ready. Must users use vue-clipboards when the copy-text-data is ready?

Actually, I can make fake data for the vue clipboard to copy inside mounted. But it is not a good way. Could you please handle this situation where the copy data is not ready for vue-clipboards. Thanks!

Btw, the version I am using is 1.2.4

**Comment by Inndy** [comment]
Well, as you can see, our latest release is [v0.2.1](https://github.com/Inndy/vue-clipboard2/releases).

I'm afraid of that I can't help you before we have a `v1.2.4` release.

**Comment by Inndy** [comment]
If you have any problem with `vue-clipbaords`, report it at https://github.com/zhuowenli/vue-clipboards
