### ISSUE TITLE
ios9 无法复制

### ISSUE THREAD

**Issue by Thomastar** [Inndy/vue-clipboard2#43]
ios9 无法复制
代码：
`        this.$copyText(text).then(function (e) {
          //success
          console.log('1')
          _this.copyVisible = true
          _this.copyTips = '复制成功'
        }, function (e) {
          //error
          console.log(e)
        })  `

**Comment by Inndy** [comment]
According to Vue.js:

> #### Browser Compatibility
> Vue.js supports all browsers that are [ES5-compliant](http://kangax.github.io/compat-table/es5/) (IE8 and below are not supported).

And from clipboard.js

> ## Browser Support
> This library relies on both [Selection](https://developer.mozilla.org/en-US/docs/Web/API/Selection) and [execCommand](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand) APIs. The first one is [supported by all browsers](http://caniuse.com/#search=selection) while the second one is supported in the following browsers.

iOS 9 is considered obsolete and will not be supported. (Which is also impossible to do so due to lack of support to clipboard API)
