### ISSUE TITLE
事件冒泡

### ISSUE THREAD

**Issue by xuchao321** [Inndy/vue-clipboard2#46]
复制的时候如何阻止事件冒泡

**Comment by MAJIANYANG666** [comment]
安卓手机复制文字之后只能粘贴一次。之后再复制就不能粘贴了。请问如何解决？苹果手机可以正常使用

**Comment by skjnldsv** [comment]
Same issue here.
It seems that it doesn't work.

I'm using this alongside vue-click-outside, and my menu is still getting closes. (other menu entries using the same `@click.stop.prevent` works well)

**Comment by Inndy** [comment]
@skjnldsv Can you provide a minimal reproduce so I can inspect and debug?

**Comment by skjnldsv** [comment]
@Inndy Sure :)
https://codesandbox.io/s/vue-clickoutside-clipboard-issue-hzwyf

Open the menu, click the button, you get an alert and the menu stays opened.
Now click the 'Copy link' entry, text is copied, but menu closes :)

**Comment by Inndy** [comment]
`$copyText` have to create a temporary element and fire a click event which will also be captured by `vue-clickoutside`. In this case, solution was attached below:

```html
<template>
  <div id="app">
    <div v-click-outside="closeMenu">
      <a
        href="#"
        class="menu-button"
        @click.prevent="toggleMenu"
      >Open menu</a>
      <div v-show="opened" class="menu">
        <ul>
          <li>
            <a href="#https://url-to-copy.io" v-clipboard:copy="'text to copy'">{{copyButtonText}}</a>
          </li>
          <li>
            <button @click.stop.prevent="alert">Click to do something</button>
          </li>
        </ul>
      </div>
    </div>
  </div>
</template>
```

**Comment by skjnldsv** [comment]
@Inndy Thanks!
Unfortunately the menu items are external components and I cannot add v-clipboard:copy to it.
Is there a way to use a specific element instead of adding a temp element to the body?
