### ISSUE TITLE
Use in Bootstrap Modals

### ISSUE THREAD

**Issue by sebestenyb** [Inndy/vue-clipboard2#5]
Hi,

I'm having some issues using this directive in a Bootstrap modal window.
According to the clipboard.js [documentation](https://clipboardjs.com/#advanced-usage), we have to define the container in this case:

> For use in Bootstrap Modals or with any other library that changes the focus you'll want to set the focused element as the container value.

```
new Clipboard('.btn', {
    container: document.getElementById('modal')
});
```

Is there a way to pass the container reference?

Thanks, I appreciate your help!

Cheers, Sebi

**Comment by Inndy** [comment]
You should use `clipboard.js` directly since this package does not handle native DOM.

**Comment by toolaugh** [comment]
the same question with me. How to pass the container reference
