### ISSUE TITLE
在火狐浏览器上不兼容，复制不成功

### ISSUE THREAD

**Issue by lizhanjie1314** [Inndy/vue-clipboard2#52]
提示：document.execCommand('cut'/'copy') 被拒绝，因为它不是从短时运行的用户生成的事件处理程序内部进行调用。
onClick写在一个弹窗中，这个也是用户触发呢，代码如下：
 onClick: function () {
                                        _this.$copyText( cardNo ).then( e =>{
                                                _this.$tip('您的卡号已复制');
                                            },e =>{
                                                _this.$tip('复制异常，请重试');
                                        })
                                    }

辛苦帮忙看看，谢谢

**Comment by Josie-ljw** [comment]
v-clipboard:copy="'内容'"这个方式是可以再火狐下复制的。但是我的场景是点击之后要去请求的，不是一段写死的文字，所以还在想怎么解决。

**Comment by Josie-ljw** [comment]
> 提示：document.execCommand('cut'/'copy') 被拒绝，因为它不是从短时运行的用户生成的事件处理程序内部进行调用。
> onClick写在一个弹窗中，这个也是用户触发呢，代码如下：
> onClick: function () {
> _this.$copyText( cardNo ).then( e =>{
> _this.$tip('您的卡号已复制');
> },e =>{
> _this.$tip('复制异常，请重试');
> })
> }
> 
> 辛苦帮忙看看，谢谢

------------------------------------------------------------------------------
这个问题是这样的，火狐，Safari浏览器里需要用户主动触发复制粘贴事件，我之前失败是因为我复制的是请求之后的数据，而请求这个行为就被浏览器视为非用户直接触发，所以会失败。
解决方案：跟交互沟通，加一个确认气泡（轻量的），在弹出气泡的时候就已经请求好数据了，然后点击确认的时候，再去进行复制。希望可以帮到你~

**Comment by lizhanjie1314** [comment]
好的，感谢解答。
