### ISSUE TITLE
core.js

### ISSUE THREAD

**Issue by ggoog** [Inndy/vue-clipboard2#53]
WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.
You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:

**Comment by Inndy** [comment]
We don't have any dependencies to either `babel` nor `corejs`
