### ISSUE TITLE
自定义 promise 中回调 this.$copyText 不执行

### ISSUE THREAD

**Issue by accardo** [Inndy/vue-clipboard2#57]
customProperty(data).then((xhr) => { 
         this.copyPassText(xhr.data)   
      });

this.$copyText(data).then(function(e){
//这里不会执行
})

**Comment by fattoliu** [comment]
额，我也遇到这个问题了，但是我在浏览器中可以的，vue+cordova 打包成 app，装到 android 手机上就不行了

**Comment by Inndy** [comment]
https://github.com/Inndy/vue-clipboard2#i-want-to-copy-texts-without-a-specific-button

$copyText will not work in async events. Make sure the calling stack is direct from `onClick` event.

The solution will be loading content first and displaying a copy button.

**Comment by v-haijiang9999** [comment]
我也遇到这个问题。调用后台接口后，获取到链接，在复制$copyText。就不成功。不调用后台接口直接$copyText，就好使。

**Comment by SimonWang2014** [comment]
提个问题，我用jQuery的同步ajax请求的回调中复制文本，在ios和电脑浏览器上没问题，但是在android手机浏览器中不能复制，错误信息也看不到

**Comment by accardo** [comment]
> https://github.com/Inndy/vue-clipboard2#i-want-to-copy-texts-without-a-specific-button
> 
> $copyText will not work in async events. Make sure the calling stack is direct from `onClick` event.
> 
> The solution will be loading content first and displaying a copy button.

This problem is triggered because there is no event trigger.

**Comment by Inndy** [comment]
If you have problem with `$copyText` method, please open an new issue with minimal reproduction sample. Consider issue was solved.
