### ISSUE TITLE
v-clipboard:cut is not work

### ISSUE THREAD

**Issue by ZQCinderella** [Inndy/vue-clipboard2#60]
如果binding.args是cut的话，实际上是不生效的，没有复制成功，也没有剪切成功

**Comment by Inndy** [comment]
This binding library do not support `cut` operation since it takes input form variables. You can clear data in the input box after the copy operation succeed. Otherwise you should use `clipboard.js` directly.

**Comment by ZQCinderella** [comment]
I see and thank you for your explanation------------------ 原始邮件 ------------------
发件人: "Inndy"<notifications@github.com>
发送时间: 2019年6月25日(星期二) 中午1:53
收件人: "Inndy/vue-clipboard2"<vue-clipboard2@noreply.github.com>;
抄送: "fenget"<604017846@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Inndy/vue-clipboard2] v-clipboard:cut is not work (#60)



This binding library do not support cut operation since it takes input form variables. You can clear data in the input box after the copy operation succeed. Otherwise you should use clipboard.js directly.
 
&mdash;
