### ISSUE TITLE
cannot copy the text on phone if throght network gateway which the text start with http://

### ISSUE THREAD

**Issue by xingyueiwj** [Inndy/vue-clipboard2#62]
cannot copy the text on phone if throght network gateway which the text start with http:// 
how can id do ?
i set like this 
new Vue({
    el: '#app',
    template: '#t',
    data: function () {
      return {
        message: 'http://test.xxx.com/seal/#/yyy/clPoXCDt9WiPRcyov4ZT%2Fw%3D%3D/666'
      }
    },
    methods: {
      done: function () {
        alert('Copied!')
      }
    }
  })

but i get this on wechat
/an:testxxx/seal/#/yyy/clPoXCDt9WiPRcyov4ZT%2Fw%3D%3D/666
why ???!

**Comment by Inndy** [comment]
Wechat did that. No my problem.

**Comment by xingyueiwj** [comment]
ok,thank you very much!


------------------ 原始邮件 ------------------
发件人: "Inndy"<notifications@github.com>;
发送时间: 2019年6月25日(星期二) 中午1:50
收件人: "Inndy/vue-clipboard2"<vue-clipboard2@noreply.github.com>;
抄送: "我的爱界"<ywb10.8@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Inndy/vue-clipboard2] cannot copy the text on phone if throghtnetwork gateway which the text start with http:// (#62)




Wechat did that. No my problem.
