### ISSUE TITLE
安装依赖的时候引用错误

### ISSUE THREAD

**Issue by iamwo0** [Inndy/vue-clipboard2#66]
* 项目中使用yarn add了 vue-clipboard2, 成功安装并使用.
* 然后因为种种原因在项目目录下面再次执行yarn或者yarn upgrade某个库的时候,会提示让选择clipboard.js的版本,只有1.0.1和1.0.0可选.
* 查看vue-clipboard2依赖的是clipboard ^2.0.0的库.
* 仔细查找,是yarn默认找了一个叫clipboard.js的库[clipboard.js](https://yarnpkg.com/en/package/clipboard.js), 如图: 
![image](https://user-images.githubusercontent.com/5955586/63342177-6ab3b000-c37d-11e9-951f-e5d985acce5b.png)

.请确认并修复.

**Comment by Inndy** [comment]
Npm package "clipboard.js" is not in this project. Please check [package.json](https://github.com/Inndy/vue-clipboard2/blob/master/package.json#L29)

**Comment by iamwo0** [comment]
My plugin file name error, not bug; close issue
