### ISSUE TITLE
This relative module was not found:

### ISSUE THREAD

**Issue by brainkode** [Inndy/vue-clipboard2#7]
This relative module was not found:

* ./clipboard-action in ./node_modules/vue-clipboard2/dist/vue-clipboard.min.js
I use webpack, first time when i use npm run dev it works. but i use npm run prod an have errors now when i use npm run dev i have this error why is that ?

**Comment by Inndy** [comment]
Did you check the webpack config between development and production?

**Comment by Inndy** [comment]
@brainkode Still have the issue?
