### ISSUE TITLE
how to select text from a block, like copy syntax highlight by prismjs? 

### ISSUE THREAD

**Issue by ironshashi** [Inndy/vue-clipboard2#73]
I am using vue-prism-component [https://www.npmjs.com/package/vue-prism-component] and I want to add a button that should copy the syntax. But I found that vue-clipboard2 copy data with the help of v-model and it is useful for copy single line text. How we can select whole block.

In my component I have this 
```
<prism language="markup">
&lt;div class=&quot;row mb-6&quot;&gt;
	&lt;div class=&quot;col sm:w-1/3 w-full&quot;&gt;
		&lt;span&gt;First Name&lt;/span&gt;
	&lt;/div&gt;
	&lt;div class=&quot;col sm:w-2/3 w-full&quot;&gt;
		&lt;input class=&quot;w-full&quot; icon-pack=&quot;feather&quot; icon=&quot;icon-user&quot; icon-no-border v-model=&quot;input5&quot; /&gt;
	&lt;/div&gt;
&lt;/div&gt;
</prism>
```

and this is in my browser 

```
<div class="row mb-6">
	<div class="col sm:w-1/3 w-full">
		<span>First Name</span>
	</div>
	<div class="col sm:w-2/3 w-full">
		<input class="w-full" icon-pack="feather" icon="icon-user" icon-no-border v-model="input5" />
	</div>
</div>
```

I want to copy the browser's syntax please help.

**Comment by Inndy** [comment]
Get `innerText` attribute from raw DOM of `<prism>` tag and use `$copyText`

**Comment by Inndy** [comment]
Update: You should use `textContent` attribute instead of `innerText` and here is [why](https://stackoverflow.com/questions/35213147/difference-between-textcontent-vs-innertext).
