### ISSUE TITLE
Success and error firing on startup

### ISSUE THREAD

**Issue by Loschcode** [Inndy/vue-clipboard2#8]
I've this code in my Vue

```
<a href="#" v-clipboard:copy="`some text`" v-clipboard:success="handleCopyStatus(true)" v-clipboard:error="handleCopyStatus(false)">Copy</a>
```
and under the Javascript script I've this part

```
methods: {
  handleCopyStatus(status) {
    console.log(status);
    this.copied = status
  }
}
```

I noticed the `console.log` was fired setting the `copied` to `true` and `false` successively. Then when I click on my `Copy` button it actually doesn't change the `copied` value. The copy to clipboard does work tho.

What's happening here ? Is it a bug ?

PS : I'm new to VueJS so I might have done something wrong.

**Comment by franzwilhelm** [comment]
Got this issue too!

**Comment by franzwilhelm** [comment]
@Inndy ?

**Comment by franzwilhelm** [comment]
@Loschcode seems like it works if you create separate functions for success and error, and reference them by method name without `()`

**Comment by Inndy** [comment]
Can you provide a minimal working example for me?

**Comment by Loschcode** [comment]
@franzwilhelm I did that indeed, forgot to give the solution here ...

`<a href="#" v-clipboard:copy="`Copy me`" v-clipboard:success="copySuccess" v-clipboard:error="copyFail">My Button</a>`

Hope it helps.

**Comment by sangdth** [comment]
I followed this solution, but it only update successful status after I click on another button. I mean, it does not update instantly when I click the copy button, but it will update if I click any button after that.

Any idea?

**Comment by ctf0** [comment]
the solution is to use it exactly as the in the docs
```vue
v-clipboard:copy="abc"
v-clipboard:success="onCopy"
```
```js
onCopy(e) {
   console.log(e)
},
```
which will produce

```bash
{action: "copy", text: "abc", trigger: td, clearSelection: ƒ}
```

**Comment by hzzly** [comment]
> 

Did you solve it? I have the same problem.

**Comment by hzzly** [comment]
> the solution is to use it exactly as in the docs
> 
> ```
> v-clipboard:copy="abc"
> v-clipboard:success="onCopy"
> ```
> 
> ```js
> onCopy(e) {
>    console.log(e)
> },
> ```
> 
> which will produce
> 
> ```shell
> {action: "copy", text: "abc", trigger: el, clearSelection: ƒ}
> ```

Did you solve it? I have the same problem.
