### ISSUE TITLE
[Question] Arrow function instead of function

### ISSUE THREAD

**Issue by NickeManarin** [Inndy/vue-clipboard2#83]
Hi, this is not an issue. I just want to understand something.

I was trying to follow the second sample from the readme, but I got a strange error. 
The `this` was `undefined`, so I could not access my properties and other methods.

Upon switching from `then(function (e) { })` to `then((e) => { })`, I can access my variable again with `this` normally. 

What's happening?

**Comment by Inndy** [comment]
In short, `this` in an arrow function will be automatically bind to current `this` when the arrow function was created.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#No_separate_this

**Comment by NickeManarin** [comment]
Thanks.
