### ISSUE TITLE
移动端夸克浏览器无法复制

### ISSUE THREAD

**Issue by ICanSayNice** [Inndy/vue-clipboard2#86]
安卓一加7Pro,安装的夸克浏览器,无法就行复制,PC端,其他测试机,都可以复制.望解答

**Comment by ICanSayNice** [comment]
安卓一加7Pro,安装的夸克浏览器,无法进行复制,PC端,其他测试机,都可以复制.望解答

**Comment by exwangwei** [comment]
> 安卓一加7Pro,安装的夸克浏览器,无法进行复制,PC端,其他测试机,都可以复制.望解答

浏览器内核问题  pc上IE10以下也不兼容  夸克浏览器内核比较低

**Comment by Inndy** [comment]
Please check your browser kernel version
