### ISSUE TITLE
请问将来会支援在Vue3的使用么？

### ISSUE THREAD

**Issue by superman285** [Inndy/vue-clipboard2#89]

**Comment by Inndy** [comment]
I'm not working in web front-end field currently, but I will try to catch up new API in my free time.

**Comment by superman285** [comment]
> I'm not working in web front-end field currently, but I will try to catch up new API in my free time.

OK, I see, thanks for your reply ! If I have time, maybe I will try to investigate how to use Vue3.

**Comment by superman285** [comment]
> I'm not working in web front-end field currently, but I will try to catch up new API in my free time.

OK, I see, thanks for your reply ! If I have time, maybe I will try to investigate how to use the plugin on Vue3.
