### ISSUE TITLE
Unable to copy large text/json file

### ISSUE THREAD

**Issue by jofftiquez** [Inndy/vue-clipboard2#9]
Is there like a limit to how large this plugin can copy? When copying small text/json it works fine. But when copying large texts, it fails. Also there are no specific error message thrown.

To help you see what happened, I am trying to copy a `3000` length json file each item is an object with 4 fields `email`, `mobileNo`, `firstName`, `lastName`. 

**Object**
```
{
    "email": "foo@bar.com",
    "mobile": "1234567",
    "firstName": "Emma",
    "lastName": "Stone"
}
... 2999 more
```

**Comment by Inndy** [comment]
Seems that you can't copy long string with clipboard API and I don't know why

Ref: http://jsbin.com/mafujiyuva/edit?html,js,output

**Comment by jofftiquez** [comment]
@Inndy Is this snippet from clipboard api? Weird.

**Comment by Inndy** [comment]
I think that is a limitation from browser. Same code works on firefox!

ref: https://github.com/zeroclipboard/zeroclipboard/issues/529

**Comment by jofftiquez** [comment]
@Inndy I was using the latest version of chrome. Anyways I will try to make more repro and get back here.
